spring.application.name=ecomonitoring

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/ecomonitoring
spring.datasource.username=postgres
spring.datasource.password=postgres

# Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# PostGIS
spring.jpa.properties.hibernate.integration.enable.spatial=true

# Telegram Bot
telegram.bot.token=???_?????_??_BOT_FATHER
telegram.bot.username=???_USERNAME_????
telegrambots.enabled=true