spring.application.name=ecomonitoring

# PostgreSQL
spring.datasource.url=jdbc:postgresql://5.42.100.155:5432/ecomonitoring
spring.datasource.username=gen_user
spring.datasource.password=Lvbnhbq1976
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.default_schema=public

# PostGIS
spring.jpa.properties.hibernate.integration.enable.spatial=true

# VK Bot
vk.access.token=vk1.a.ca0N22eO3Y7kfoDwkuVxSDJEhLJDG73_v-PFl6w9U_294lVPMVPejZmt-nN6rI4E6tn8-rvx-9vf4lYRuyNDEyxqt9X-8sQXhNoeQXbYe_wjR39BMlNoy-LQeVHoIsF4ofo3m-yq9L6RitVSE8Phj7SoA7uC8hccYtpuU-N157B_nsN8sbST8skLYMIQKSRZ0dQsdRUfV6RuwouBKSIzQA
vk.group.id=238645710
vk.longpoll.wait=25

#server
server.address=0.0.0.0
server.port=8080